export const COURSE_PAGE = {
  title: 'Khóa học',
  subtitle: 'Khám phá các khóa học blockchain và Web3',
  searchPlaceholder: 'Tìm khóa học hoặc giảng viên...',
  filterTagAll: 'Tất cả chủ đề',
  filterRatingAll: 'Tất cả đánh giá',
  filterRating4: '4+ sao',
  filterRating45: '4.5+ sao',
  sortNewest: 'Mới nhất',
  sortPopular: 'Phổ biến',
  sortPrice: 'Giá',
  emptyText: 'Không tìm thấy khóa học nào',
  enrollText: 'Đăng ký',
  viewText: 'Xem chi tiết',
  freeText: 'Miễn phí',
  lessonsText: 'bài học',
  studentsText: 'học viên',
  instructorLabel: 'Giảng viên',
} as const;

export const COURSE_DETAIL = {
  descriptionTitle: 'Mô tả khóa học',
  objectivesTitle: 'Bạn sẽ học được gì',
  requirementsTitle: 'Yêu cầu',
  chaptersTitle: 'Nội dung khóa học',
  instructorTitle: 'Giảng viên',
  reviewsTitle: 'Đánh giá từ học viên',
  enrollButton: 'Đăng ký ngay',
  enrollFreeButton: 'Đăng ký miễn phí',
  startButton: 'Bắt đầu học',
  continueButton: 'Tiếp tục học',
  completedText: 'Đã hoàn thành',
  progressText: 'Tiến độ',
  lessonsText: 'bài học',
  hoursText: 'giờ',
  studentsText: 'học viên',
  lastUpdatedText: 'Cập nhật',
  previewText: 'Xem trước',
  lecturesText: 'bài giảng',
  totalText: 'Tổng cộng',
  expandAll: 'Mở tất cả',
  collapseAll: 'Thu gọn',
  helpfulText: 'Hữu ích',
  writeReviewText: 'Viết đánh giá',
  allReviewsText: 'Xem tất cả đánh giá',
  backToCourses: 'Quay lại danh sách',
  shareText: 'Chia sẻ',
  wishlistText: 'Yêu thích',
} as const;

export const COURSE_GRID = {
  FIRST_PAGE_SIZE: 7,
  OTHER_PAGE_SIZE: 6,
  CLASSES_7: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_6: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:row-start-3',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_5: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:row-start-3',
    'sm:col-span-2 sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_4: [
    'sm:col-span-3 sm:row-span-2',
    'sm:col-span-2 sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:col-start-3 sm:row-start-3',
    'sm:col-span-2 sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_3: [
    'sm:col-span-2',
    '',
    '',
  ],
  CLASSES_2: [
    '',
    '',
  ],
  CLASSES_1: [
    '',
  ],
} as const;
