import { Course } from '@/types/course';
import { SYSTEM_CONFIG } from './config';

export const COURSE_PAGE = {
  title: 'Khóa học',
  subtitle: 'Khám phá các khóa học blockchain và Web3',
  searchPlaceholder: 'Tìm khóa học hoặc giảng viên...',
  filterTagAll: 'Tất cả chủ đề',
  filterRatingAll: 'Tất cả đánh giá',
  filterRating4: '4+ sao',
  filterRating45: '4.5+ sao',
  sortNewest: 'Mới nhất',
  sortPopular: 'Phổ biến',
  sortPrice: 'Giá',
  emptyText: 'Không tìm thấy khóa học nào',
  enrollText: 'Đăng ký',
  viewText: 'Xem chi tiết',
  freeText: 'Miễn phí',
  lessonsText: 'bài học',
  studentsText: 'học viên',
  instructorLabel: 'Giảng viên',
} as const;

export const COURSE_DETAIL = {
  descriptionTitle: 'Mô tả khóa học',
  objectivesTitle: 'Bạn sẽ học được gì',
  requirementsTitle: 'Yêu cầu',
  chaptersTitle: 'Nội dung khóa học',
  instructorTitle: 'Giảng viên',
  reviewsTitle: 'Đánh giá từ học viên',
  enrollButton: 'Đăng ký ngay',
  enrollFreeButton: 'Đăng ký miễn phí',
  startButton: 'Bắt đầu học',
  continueButton: 'Tiếp tục học',
  completedText: 'Đã hoàn thành',
  progressText: 'Tiến độ',
  lessonsText: 'bài học',
  hoursText: 'giờ',
  studentsText: 'học viên',
  lastUpdatedText: 'Cập nhật',
  previewText: 'Xem trước',
  lecturesText: 'bài giảng',
  totalText: 'Tổng cộng',
  expandAll: 'Mở tất cả',
  collapseAll: 'Thu gọn',
  helpfulText: 'Hữu ích',
  writeReviewText: 'Viết đánh giá',
  allReviewsText: 'Xem tất cả đánh giá',
  backToCourses: 'Quay lại danh sách',
  shareText: 'Chia sẻ',
  wishlistText: 'Yêu thích',
} as const;

export const COURSE_GRID = {
  FIRST_PAGE_SIZE: 7,
  OTHER_PAGE_SIZE: 6,
  CLASSES_7: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_6: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:row-start-3',
    'sm:row-span-2 sm:row-start-5',
    'sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_5: [
    'sm:col-span-3 sm:row-span-2',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:row-start-3',
    'sm:col-span-2 sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_4: [
    'sm:col-span-3 sm:row-span-2',
    'sm:col-span-2 sm:row-span-2 sm:row-start-3',
    'sm:row-span-4 sm:col-start-3 sm:row-start-3',
    'sm:col-span-2 sm:row-span-2 sm:row-start-5',
  ],
  CLASSES_3: [
    'sm:col-span-2',
    '',
    '',
  ],
  CLASSES_2: [
    'sm:col-span-2',
    'sm:col-span-2',
  ],
  CLASSES_1: [
    '',
  ],
} as const;

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: 'Blockchain cơ bản cho người mới bắt đầu',
    description: 'Tìm hiểu các khái niệm cơ bản về blockchain, cách hoạt động và ứng dụng trong thực tế. Khóa học này sẽ giúp bạn nắm vững nền tảng để tiến xa hơn.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Văn A',
    totalLessons: 12,
    totalStudents: 1234,
    rating: 4.8,
    tags: ['Blockchain', 'Cơ bản'],
    status: 'PUBLISHED',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    title: 'Smart Contract với Plutus',
    description: 'Học cách viết smart contract trên Cardano sử dụng ngôn ngữ Plutus.',
    thumbnail: '',
    price: 50,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 20,
    instructorName: 'Trần Thị B',
    totalLessons: 24,
    totalStudents: 567,
    rating: 4.9,
    tags: ['Smart Contract', 'Plutus', 'Nâng cao'],
    status: 'PUBLISHED',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    title: 'DApp Development trên Cardano',
    description: 'Xây dựng ứng dụng phi tập trung hoàn chỉnh trên nền tảng Cardano.',
    thumbnail: '',
    price: 100,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Lê Văn C',
    totalLessons: 36,
    totalStudents: 345,
    rating: 4.7,
    tags: ['DApp', 'Full-stack', 'Nâng cao'],
    status: 'PUBLISHED',
    createdAt: '2024-03-01',
  },
  {
    id: '4',
    title: 'NFT và Marketplace',
    description: 'Tạo và phát triển NFT marketplace trên Cardano.',
    thumbnail: '',
    price: 75,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Phạm Văn D',
    totalLessons: 18,
    totalStudents: 432,
    rating: 4.6,
    tags: ['NFT', 'Marketplace'],
    status: 'PUBLISHED',
    createdAt: '2024-04-01',
  },
  {
    id: '5',
    title: 'Tokenomics và DeFi',
    description: 'Hiểu về tokenomics và tài chính phi tập trung.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Thị E',
    totalLessons: 15,
    totalStudents: 678,
    rating: 4.5,
    tags: ['DeFi', 'Tokenomics'],
    status: 'PUBLISHED',
    createdAt: '2024-05-01',
  },
  {
    id: '6',
    title: 'Aiken Smart Contract',
    description: 'Viết smart contract hiệu quả với Aiken.',
    thumbnail: '',
    price: 80,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 10,
    instructorName: 'Nguyễn Văn F',
    totalLessons: 20,
    totalStudents: 234,
    rating: 4.8,
    tags: ['Aiken', 'Smart Contract'],
    status: 'PUBLISHED',
    createdAt: '2024-06-01',
  },
  {
    id: '7',
    title: 'Cardano CLI Masterclass',
    description: 'Thành thạo Cardano CLI cho developer.',
    thumbnail: '',
    price: 45,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Văn G',
    totalLessons: 16,
    totalStudents: 189,
    rating: 4.7,
    tags: ['CLI', 'DevOps'],
    status: 'PUBLISHED',
    createdAt: '2024-07-01',
  },
  {
    id: '8',
    title: 'Web3 Frontend với React',
    description: 'Kết nối frontend React với blockchain Cardano.',
    thumbnail: '',
    price: 60,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Lê Thị H',
    totalLessons: 22,
    totalStudents: 456,
    rating: 4.6,
    tags: ['React', 'Web3', 'Frontend'],
    status: 'PUBLISHED',
    createdAt: '2024-08-01',
  },
  {
    id: '9',
    title: 'Cardano Node Operation',
    description: 'Vận hành và quản lý Cardano Node.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Phạm Văn I',
    totalLessons: 14,
    totalStudents: 321,
    rating: 4.5,
    tags: ['Node', 'Infrastructure'],
    status: 'PUBLISHED',
    createdAt: '2024-09-01',
  },
  {
    id: '10',
    title: 'Stake Pool Operation',
    description: 'Hướng dẫn vận hành Stake Pool trên Cardano.',
    thumbnail: '',
    price: 120,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Văn K',
    totalLessons: 28,
    totalStudents: 178,
    rating: 4.9,
    tags: ['Stake Pool', 'SPO'],
    status: 'PUBLISHED',
    createdAt: '2024-10-01',
  },
  {
    id: '11',
    title: 'Cardano Governance',
    description: 'Tìm hiểu về quản trị phi tập trung trên Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Thị L',
    totalLessons: 10,
    totalStudents: 567,
    rating: 4.4,
    tags: ['Governance', 'Voltaire'],
    status: 'PUBLISHED',
    createdAt: '2024-11-01',
  },
  {
    id: '12',
    title: 'Hydra Layer 2',
    description: 'Scaling solution với Hydra trên Cardano.',
    thumbnail: '',
    price: 90,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Lê Văn M',
    totalLessons: 18,
    totalStudents: 234,
    rating: 4.7,
    tags: ['Hydra', 'Layer 2', 'Scaling'],
    status: 'PUBLISHED',
    createdAt: '2024-12-01',
  },
  {
    id: '13',
    title: 'Mithril Protocol',
    description: 'Light client và snapshot với Mithril.',
    thumbnail: '',
    price: 55,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Văn N',
    totalLessons: 12,
    totalStudents: 145,
    rating: 4.6,
    tags: ['Mithril', 'Light Client'],
    status: 'PUBLISHED',
    createdAt: '2025-01-01',
  },
  {
    id: '14',
    title: 'Cardano Security Best Practices',
    description: 'Bảo mật ví và smart contract trên Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Văn O',
    totalLessons: 10,
    totalStudents: 289,
    rating: 4.8,
    tags: ['Security', 'Best Practices'],
    status: 'PUBLISHED',
    createdAt: '2025-02-01',
  },
  {
    id: '15',
    title: 'Marlowe cho Non-Developer',
    description: 'Tạo smart contract không cần code với Marlowe.',
    thumbnail: '',
    price: 40,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Thị P',
    totalLessons: 14,
    totalStudents: 356,
    rating: 4.5,
    tags: ['Marlowe', 'No-Code'],
    status: 'PUBLISHED',
    createdAt: '2025-03-01',
  },
  {
    id: '16',
    title: 'Catalyst Proposal Writing',
    description: 'Viết proposal thành công trên Project Catalyst.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Lê Văn Q',
    totalLessons: 8,
    totalStudents: 423,
    rating: 4.7,
    tags: ['Catalyst', 'Proposal'],
    status: 'PUBLISHED',
    createdAt: '2025-04-01',
  },
  {
    id: '17',
    title: 'Cardano dApp Testing',
    description: 'Testing và QA cho ứng dụng Cardano.',
    thumbnail: '',
    price: 65,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 15,
    instructorName: 'Phạm Thị R',
    totalLessons: 16,
    totalStudents: 198,
    rating: 4.6,
    tags: ['Testing', 'QA', 'dApp'],
    status: 'PUBLISHED',
    createdAt: '2025-05-01',
  },
  {
    id: '18',
    title: 'Cardano Integration APIs',
    description: 'Tích hợp Cardano vào ứng dụng với các API.',
    thumbnail: '',
    price: 70,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Văn S',
    totalLessons: 20,
    totalStudents: 267,
    rating: 4.8,
    tags: ['API', 'Integration', 'Backend'],
    status: 'PUBLISHED',
    createdAt: '2025-06-01',
  },
  {
    id: '19',
    title: 'Cardano Wallet Development',
    description: 'Xây dựng ví Cardano với các tính năng nâng cao.',
    thumbnail: '',
    price: 85,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Văn T',
    totalLessons: 22,
    totalStudents: 312,
    rating: 4.7,
    tags: ['Wallet', 'Development'],
    status: 'PUBLISHED',
    createdAt: '2025-07-01',
  },
  {
    id: '20',
    title: 'Cardano Data Analytics',
    description: 'Phân tích dữ liệu blockchain Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Thị U',
    totalLessons: 15,
    totalStudents: 445,
    rating: 4.5,
    tags: ['Analytics', 'Data', 'Blockchain'],
    status: 'PUBLISHED',
    createdAt: '2025-08-01',
  },
  {
    id: '21',
    title: 'Cardano Mobile Development',
    description: 'Phát triển ứng dụng mobile tích hợp Cardano.',
    thumbnail: '',
    price: 95,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 20,
    instructorName: 'Lê Văn V',
    totalLessons: 28,
    totalStudents: 234,
    rating: 4.8,
    tags: ['Mobile', 'React Native', 'Flutter'],
    status: 'PUBLISHED',
    createdAt: '2025-09-01',
  },
  {
    id: '22',
    title: 'Cardano Enterprise Solutions',
    description: 'Giải pháp blockchain cho doanh nghiệp với Cardano.',
    thumbnail: '',
    price: 150,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Phạm Văn X',
    totalLessons: 32,
    totalStudents: 156,
    rating: 4.9,
    tags: ['Enterprise', 'Business', 'Solutions'],
    status: 'PUBLISHED',
    createdAt: '2025-10-01',
  },
  {
    id: '23',
    title: 'Zero Knowledge Proofs trên Cardano',
    description: 'Tìm hiểu và ứng dụng Zero Knowledge Proofs để tăng cường bảo mật và quyền riêng tư trên Cardano.',
    thumbnail: '',
    price: 110,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Văn Y',
    totalLessons: 24,
    totalStudents: 189,
    rating: 4.8,
    tags: ['ZK Proofs', 'Privacy', 'Cryptography'],
    status: 'PUBLISHED',
    createdAt: '2025-11-01',
  },
  {
    id: '24',
    title: 'Cardano Sidechains Development',
    description: 'Xây dựng và triển khai sidechains trên Cardano để mở rộng khả năng và tính năng của hệ thống.',
    thumbnail: '',
    price: 130,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 15,
    instructorName: 'Lê Thị Z',
    totalLessons: 26,
    totalStudents: 145,
    rating: 4.7,
    tags: ['Sidechains', 'Scaling', 'Development'],
    status: 'PUBLISHED',
    createdAt: '2025-12-01',
  },
  {
    id: '25',
    title: 'Cardano dRep và Governance',
    description: 'Trở thành Delegated Representative (dRep) và tham gia quản trị phi tập trung trên Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Văn W',
    totalLessons: 12,
    totalStudents: 534,
    rating: 4.6,
    tags: ['dRep', 'Governance', 'Voltaire'],
    status: 'PUBLISHED',
    createdAt: '2026-01-01',
  },
  {
    id: '26',
    title: 'Cardano Partner Chains',
    description: 'Tìm hiểu về Partner Chains và cách tích hợp các blockchain khác với hệ sinh thái Cardano.',
    thumbnail: '',
    price: 95,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Văn AA',
    totalLessons: 18,
    totalStudents: 223,
    rating: 4.8,
    tags: ['Partner Chains', 'Interoperability', 'Ecosystem'],
    status: 'PUBLISHED',
    createdAt: '2026-02-01',
  },
  {
    id: '27',
    title: 'Cardano Gaming & Metaverse',
    description: 'Phát triển game và ứng dụng metaverse trên nền tảng Cardano với NFT và token.',
    thumbnail: '',
    price: 85,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 10,
    instructorName: 'Phạm Văn BB',
    totalLessons: 20,
    totalStudents: 378,
    rating: 4.7,
    tags: ['Gaming', 'Metaverse', 'NFT'],
    status: 'PUBLISHED',
    createdAt: '2026-03-01',
  },
  {
    id: '28',
    title: 'Cardano Real World Assets',
    description: 'Tokenization và quản lý tài sản thực (Real World Assets) trên Cardano blockchain.',
    thumbnail: '',
    price: 120,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Thị CC',
    totalLessons: 22,
    totalStudents: 267,
    rating: 4.9,
    tags: ['RWA', 'Tokenization', 'Finance'],
    status: 'PUBLISHED',
    createdAt: '2026-04-01',
  },
  {
    id: '29',
    title: 'Cardano Identity Solutions',
    description: 'Xây dựng hệ thống định danh phi tập trung (DID) trên Cardano.',
    thumbnail: '',
    price: 75,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Văn DD',
    totalLessons: 16,
    totalStudents: 198,
    rating: 4.6,
    tags: ['Identity', 'DID', 'Privacy'],
    status: 'PUBLISHED',
    createdAt: '2026-05-01',
  },
  {
    id: '30',
    title: 'Cardano Oracle Integration',
    description: 'Tích hợp Oracle để đưa dữ liệu thực vào smart contract trên Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Thị EE',
    totalLessons: 14,
    totalStudents: 312,
    rating: 4.7,
    tags: ['Oracle', 'Data', 'Smart Contract'],
    status: 'PUBLISHED',
    createdAt: '2026-06-01',
  },
  {
    id: '31',
    title: 'Cardano Cross-Chain Bridges',
    description: 'Xây dựng và sử dụng bridge để kết nối Cardano với các blockchain khác.',
    thumbnail: '',
    price: 100,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 20,
    instructorName: 'Lê Văn FF',
    totalLessons: 20,
    totalStudents: 245,
    rating: 4.8,
    tags: ['Bridge', 'Cross-Chain', 'Interoperability'],
    status: 'PUBLISHED',
    createdAt: '2026-07-01',
  },
  {
    id: '32',
    title: 'Cardano DAO Development',
    description: 'Tạo và quản lý Decentralized Autonomous Organization trên Cardano.',
    thumbnail: '',
    price: 90,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Phạm Văn GG',
    totalLessons: 18,
    totalStudents: 187,
    rating: 4.7,
    tags: ['DAO', 'Governance', 'Community'],
    status: 'PUBLISHED',
    createdAt: '2026-08-01',
  },
  {
    id: '33',
    title: 'Cardano AI & Machine Learning',
    description: 'Kết hợp AI và Machine Learning với blockchain Cardano cho các ứng dụng thông minh.',
    thumbnail: '',
    price: 140,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Văn HH',
    totalLessons: 26,
    totalStudents: 334,
    rating: 4.9,
    tags: ['AI', 'Machine Learning', 'Blockchain'],
    status: 'PUBLISHED',
    createdAt: '2026-09-01',
  },
  {
    id: '34',
    title: 'Cardano Supply Chain',
    description: 'Ứng dụng blockchain Cardano trong quản lý chuỗi cung ứng và truy xuất nguồn gốc.',
    thumbnail: '',
    price: 85,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Nguyễn Thị II',
    totalLessons: 18,
    totalStudents: 256,
    rating: 4.6,
    tags: ['Supply Chain', 'Traceability', 'Enterprise'],
    status: 'PUBLISHED',
    createdAt: '2026-10-01',
  },
  {
    id: '35',
    title: 'Cardano Healthcare Solutions',
    description: 'Phát triển ứng dụng y tế và quản lý hồ sơ bệnh án trên Cardano.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Trần Văn KK',
    totalLessons: 14,
    totalStudents: 189,
    rating: 4.5,
    tags: ['Healthcare', 'Medical', 'Privacy'],
    status: 'PUBLISHED',
    createdAt: '2026-11-01',
  },
  {
    id: '36',
    title: 'Cardano Education Platform',
    description: 'Xây dựng nền tảng giáo dục với chứng chỉ NFT và học phí crypto.',
    thumbnail: '',
    price: 70,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    discount: 15,
    instructorName: 'Lê Thị LL',
    totalLessons: 16,
    totalStudents: 423,
    rating: 4.8,
    tags: ['Education', 'EdTech', 'NFT Certificate'],
    status: 'PUBLISHED',
    createdAt: '2026-12-01',
  },
  {
    id: '37',
    title: 'Cardano Social Impact',
    description: 'Sử dụng Cardano cho các dự án tác động xã hội và từ thiện minh bạch.',
    thumbnail: '',
    price: 0,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Phạm Thị MM',
    totalLessons: 12,
    totalStudents: 567,
    rating: 4.7,
    tags: ['Social Impact', 'Charity', 'Transparency'],
    status: 'PUBLISHED',
    createdAt: '2027-01-01',
  },
  {
    id: '38',
    title: 'Cardano Advanced Architecture',
    description: 'Kiến trúc nâng cao và tối ưu hóa hiệu suất cho ứng dụng Cardano quy mô lớn.',
    thumbnail: '',
    price: 160,
    currency: SYSTEM_CONFIG.DEFAULT_CURRENCY,
    instructorName: 'Hoàng Văn NN',
    totalLessons: 30,
    totalStudents: 145,
    rating: 4.9,
    tags: ['Architecture', 'Performance', 'Advanced'],
    status: 'PUBLISHED',
    createdAt: '2027-02-01',
  },
];

export const getMockCourseDetail = (id: string): Course | undefined => {
  const course = MOCK_COURSES.find(c => c.id === id);
  if (!course) return undefined;
  
  return {
    ...course,
    instructorBio: `Chuyên gia blockchain với hơn 5 năm kinh nghiệm phát triển trên nền tảng Cardano. Đã tham gia nhiều dự án DeFi và NFT thành công.

Học vị: Thạc sĩ Khoa học Máy tính - Đại học Bách khoa Hà Nội
Kinh nghiệm: 5+ năm phát triển blockchain, 3+ năm làm việc với Cardano
Thành tích: Top 10 Catalyst Fund 8, Contributor tại nhiều dự án open-source
Đã đào tạo: 5,000+ học viên với tỉ lệ hài lòng 98%`,
    totalDuration: 1200,
    reviewCount: Math.floor(course.totalStudents * 0.3),
    updatedAt: '2025-01-15',
    objectives: [
      'Hiểu rõ các khái niệm cơ bản về blockchain và Cardano',
      'Nắm vững cách thức hoạt động của mạng lưới phi tập trung',
      'Có khả năng phân tích và đánh giá các dự án blockchain',
      'Xây dựng được ứng dụng đơn giản trên Cardano',
      'Hiểu về tokenomics và cơ chế staking',
    ],
    requirements: [
      'Kiến thức cơ bản về lập trình',
      'Máy tính với kết nối internet ổn định',
      'Tinh thần học hỏi và kiên nhẫn',
    ],
    chapters: [
      {
        id: 'ch1',
        title: 'Giới thiệu về Blockchain',
        orderIndex: 1,
        lectures: [
          { id: 'l1', title: 'Blockchain là gì?', duration: 15, isPreview: true, orderIndex: 1, videoUrl: 'https://www.youtube.com/watch?v=G9b2NqNp4VM' },
          { id: 'l2', title: 'Lịch sử phát triển blockchain', duration: 12, isPreview: true, orderIndex: 2, videoUrl: 'https://www.youtube.com/watch?v=G9b2NqNp4VM' },
          { id: 'l3', title: 'Các thành phần của blockchain', duration: 20, isPreview: false, orderIndex: 3 },
          { id: 'l4', title: 'Bài tập thực hành', duration: 30, isPreview: false, orderIndex: 4 },
        ],
      },
      {
        id: 'ch2',
        title: 'Cardano Fundamentals',
        orderIndex: 2,
        lectures: [
          { id: 'l5', title: 'Giới thiệu về Cardano', duration: 18, isPreview: false, orderIndex: 1 },
          { id: 'l6', title: 'Kiến trúc Cardano', duration: 25, isPreview: false, orderIndex: 2 },
          { id: 'l7', title: 'Ouroboros Consensus', duration: 22, isPreview: false, orderIndex: 3 },
          { id: 'l8', title: 'ADA và Native Tokens', duration: 20, isPreview: false, orderIndex: 4 },
        ],
      },
      {
        id: 'ch3',
        title: 'Ví và Staking',
        orderIndex: 3,
        lectures: [
          { id: 'l9', title: 'Các loại ví Cardano', duration: 15, isPreview: false, orderIndex: 1 },
          { id: 'l10', title: 'Cách thiết lập ví', duration: 20, isPreview: false, orderIndex: 2 },
          { id: 'l11', title: 'Staking là gì?', duration: 18, isPreview: false, orderIndex: 3 },
          { id: 'l12', title: 'Chọn Stake Pool', duration: 22, isPreview: false, orderIndex: 4 },
        ],
      },
      {
        id: 'ch4',
        title: 'Smart Contract cơ bản',
        orderIndex: 4,
        lectures: [
          { id: 'l13', title: 'Smart Contract là gì?', duration: 20, isPreview: false, orderIndex: 1 },
          { id: 'l14', title: 'Plutus và Aiken', duration: 25, isPreview: false, orderIndex: 2 },
          { id: 'l15', title: 'Viết smart contract đầu tiên', duration: 35, isPreview: false, orderIndex: 3 },
          { id: 'l16', title: 'Deploy và testing', duration: 40, isPreview: false, orderIndex: 4 },
        ],
      },
    ],
  };
};

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    userId: 'u1',
    userName: 'Nguyễn Minh Tuấn',
    userAvatar: '',
    rating: 5,
    content: 'Khóa học rất hay và chi tiết. Giảng viên giải thích dễ hiểu, có nhiều ví dụ thực tế. Tôi đã áp dụng được kiến thức vào dự án của mình.',
    createdAt: '2025-01-10',
    helpful: 24,
    notHelpful: 2,
    userVote: null,
    replies: [
      {
        id: 'rp1',
        userId: 'instructor1',
        userName: 'Nguyễn Văn AA',
        content: 'Cảm ơn bạn đã đánh giá! Rất vui vì khóa học đã giúp ích cho bạn.',
        createdAt: '2025-01-11',
        isInstructor: true,
      },
    ],
  },
  {
    id: 'r2',
    userId: 'u2',
    userName: 'Trần Thị Mai',
    rating: 5,
    content: 'Nội dung đầy đủ từ cơ bản đến nâng cao. Bài tập thực hành giúp củng cố kiến thức rất tốt.',
    createdAt: '2025-01-08',
    helpful: 18,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r3',
    userId: 'u3',
    userName: 'Lê Văn Hùng',
    rating: 4,
    content: 'Khóa học tốt, tuy nhiên một số phần có thể giải thích kỹ hơn. Nhìn chung vẫn rất đáng để học.',
    createdAt: '2025-01-05',
    helpful: 12,
    notHelpful: 3,
    userVote: null,
  },
  {
    id: 'r4',
    userId: 'u4',
    userName: 'Phạm Thu Hương',
    rating: 5,
    content: 'Tuyệt vời! Đây là khóa học blockchain tốt nhất mà tôi từng học. Cảm ơn giảng viên rất nhiều!',
    createdAt: '2025-01-03',
    helpful: 31,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r5',
    userId: 'u5',
    userName: 'Hoàng Minh Đức',
    rating: 5,
    content: 'Giảng viên rất nhiệt tình, bài giảng súc tích và dễ hiểu. Highly recommend!',
    createdAt: '2025-01-02',
    helpful: 15,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r6',
    userId: 'u6',
    userName: 'Vũ Thị Lan',
    rating: 4,
    content: 'Nội dung phong phú, tuy nhiên một số phần hơi nhanh. Cần xem lại nhiều lần.',
    createdAt: '2025-01-01',
    helpful: 8,
    notHelpful: 2,
    userVote: null,
  },
  {
    id: 'r7',
    userId: 'u7',
    userName: 'Đặng Văn Nam',
    rating: 5,
    content: 'Sau khi học xong khóa này, tôi đã tự tin hơn rất nhiều khi làm việc với blockchain.',
    createdAt: '2024-12-30',
    helpful: 22,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r8',
    userId: 'u8',
    userName: 'Bùi Thị Hoa',
    rating: 4,
    content: 'Khóa học hay, giá cả hợp lý. Sẽ giới thiệu cho bạn bè.',
    createdAt: '2024-12-28',
    helpful: 11,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r9',
    userId: 'u9',
    userName: 'Ngô Quang Hải',
    rating: 5,
    content: 'Đây là khóa học đầu tiên về Cardano mà tôi học và không thể hài lòng hơn!',
    createdAt: '2024-12-25',
    helpful: 19,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r10',
    userId: 'u10',
    userName: 'Trịnh Văn Tùng',
    rating: 3,
    content: 'Khóa học ổn nhưng cần cập nhật thêm nội dung mới.',
    createdAt: '2024-12-22',
    helpful: 5,
    notHelpful: 4,
    userVote: null,
  },
  {
    id: 'r11',
    userId: 'u11',
    userName: 'Lý Thị Mai',
    rating: 5,
    content: 'Rất chi tiết và chuyên nghiệp. Giảng viên giải đáp thắc mắc rất nhanh.',
    createdAt: '2024-12-20',
    helpful: 28,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r12',
    userId: 'u12',
    userName: 'Phan Văn Sơn',
    rating: 4,
    content: 'Học được nhiều kiến thức bổ ích. Cảm ơn đội ngũ giảng viên.',
    createdAt: '2024-12-18',
    helpful: 14,
    notHelpful: 2,
    userVote: null,
  },
  {
    id: 'r13',
    userId: 'u13',
    userName: 'Đinh Thị Ngọc',
    rating: 5,
    content: 'Khóa học vượt xa mong đợi của tôi. Sẽ quay lại học các khóa khác.',
    createdAt: '2024-12-15',
    helpful: 33,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r14',
    userId: 'u14',
    userName: 'Võ Minh Quân',
    rating: 4,
    content: 'Nội dung tốt, video chất lượng cao. Chỉ tiếc là không có phụ đề tiếng Việt.',
    createdAt: '2024-12-12',
    helpful: 9,
    notHelpful: 3,
    userVote: null,
  },
  {
    id: 'r15',
    userId: 'u15',
    userName: 'Đỗ Thị Hằng',
    rating: 5,
    content: 'Xuất sắc! Tôi đã apply được kiến thức vào dự án thực tế ngay sau khi học.',
    createdAt: '2024-12-10',
    helpful: 41,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r16',
    userId: 'u16',
    userName: 'Trương Văn Bình',
    rating: 4,
    content: 'Khóa học đáng giá từng đồng. Giảng viên rất am hiểu về lĩnh vực này.',
    createdAt: '2024-12-08',
    helpful: 17,
    notHelpful: 2,
    userVote: null,
  },
  {
    id: 'r17',
    userId: 'u17',
    userName: 'Mai Thị Linh',
    rating: 5,
    content: 'Cảm ơn giảng viên đã tạo ra khóa học tuyệt vời như này!',
    createdAt: '2024-12-05',
    helpful: 25,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r18',
    userId: 'u18',
    userName: 'Hồ Văn Long',
    rating: 3,
    content: 'Khóa học cơ bản, phù hợp với người mới bắt đầu.',
    createdAt: '2024-12-03',
    helpful: 7,
    notHelpful: 5,
    userVote: null,
  },
  {
    id: 'r19',
    userId: 'u19',
    userName: 'Lương Thị Yến',
    rating: 5,
    content: 'Đã học xong và nhận được chứng chỉ NFT. Rất tuyệt vời!',
    createdAt: '2024-12-01',
    helpful: 36,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r20',
    userId: 'u20',
    userName: 'Cao Minh Tuấn',
    rating: 4,
    content: 'Khóa học chất lượng, sẽ tiếp tục theo dõi các khóa học khác.',
    createdAt: '2024-11-28',
    helpful: 13,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r21',
    userId: 'u21',
    userName: 'Phùng Thị Ánh',
    rating: 5,
    content: 'Học rất vui và bổ ích. Recommend cho tất cả mọi người!',
    createdAt: '2024-11-25',
    helpful: 29,
    notHelpful: 0,
    userVote: null,
  },
  {
    id: 'r22',
    userId: 'u22',
    userName: 'Dương Văn Khoa',
    rating: 4,
    content: 'Giảng viên nhiệt tình, nội dung cập nhật theo xu hướng mới.',
    createdAt: '2024-11-22',
    helpful: 16,
    notHelpful: 2,
    userVote: null,
  },
  {
    id: 'r23',
    userId: 'u23',
    userName: 'Tạ Thị Phương',
    rating: 5,
    content: 'Chưa bao giờ học blockchain dễ hiểu đến thế!',
    createdAt: '2024-11-20',
    helpful: 44,
    notHelpful: 1,
    userVote: null,
  },
  {
    id: 'r24',
    userId: 'u24',
    userName: 'Kiều Văn Đạt',
    rating: 4,
    content: 'Khóa học hay, chỉ cần thêm một số bài tập thực hành nữa.',
    createdAt: '2024-11-18',
    helpful: 10,
    notHelpful: 3,
    userVote: null,
  },
  {
    id: 'r25',
    userId: 'u25',
    userName: 'Nguyễn Thị Thảo',
    rating: 5,
    content: '5 sao cho khóa học này. Worth every penny!',
    createdAt: '2024-11-15',
    helpful: 38,
    notHelpful: 0,
    userVote: null,
  },
];

export const MOCK_REVIEW_STATS = {
  average: 4.8,
  total: 156,
  distribution: {
    5: 98,
    4: 42,
    3: 12,
    2: 3,
    1: 1,
  },
};
